# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  upload_to_main:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          project_id: '${{ secrets.PROJECT_ID }}'

      - name: Upload file to GCS
        run: |
          gsutil cp variables.json gs://us-central1-airflow-test-gc-af5e545d-bucket/data/variables.json
          
      - name: Import Airflow Variables
        run: |
          gcloud composer environments run airflow-test-gcs \
            --location us-central1 \
              variables import -- /home/airflow/gcs/data/variables.json

      - name: Upload News Api to GCS
        run: |
          gsutil cp fetch_news_api.py gs://us-central1-airflow-test-gc-af5e545d-bucket/dags/fetch_news_api.py

      - name: Upload Airflow DAG to Airflow Dev GCS
        run: |
          gcloud composer environments storage dags import \
            --environment airflow-test-gcs \
            --location us-central1 \
            --source news_api_airflow_job.py